config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'community', to: 'pages#community'

  resources :forecast_results
  resources :weather_searches do
    resources :reviews, only: :create
  end
  resources :search_parameters
  resources :parameters
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
  <div class="navbar-lewagon <%= sticky ? 'community' : ''  %> ">
  <div>
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "vamos_logo.png" %>
    <% end %>
 </div>
  <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> -->
    <!-- <span class="navbar-toggler-icon"></span> -->
  <!-- </button> -->


  <div  id="navbarSupportedContent ">
    <ul class="navbar-nav ">
      <% if user_signed_in? %>
        <!-- <li class="nav-item active">
          <%#= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%#= link_to "Messages", "#", class: "nav-link" %>
        </li> -->
        <div class="nav-item dropdown dropdown-menu-end">
          <% if user_signed_in? && current_user.photo.attached?%>
          <%= cl_image_tag(current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false)%>
          <% else %>
          <%= image_tag "https://www.seekpng.com/png/full/428-4287240_no-avatar-user-circle-icon-png.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu">
            <%= link_to "My Dashboard", weather_searches_path, class: "dropdown-item" %>
            <%= link_to "Make new search", new_weather_search_path, class: "dropdown-item" %>
            <%= link_to "Community", community_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </div>
      <% else %>
        <div class="home-link">
          <i class="fas fa-home text-center"></i>
          <li class="nav-item">
          <%= link_to "Home", root_path, class: "home" %>
          </li>
        </div>
      <% end %>
    </ul>
  </div>
</div>