config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'community', to: 'pages#community'

  resources :forecast_results
  resources :weather_searches do
    resources :reviews, only: :create
  end
  resources :search_parameters
  resources :parameters
end

app/models/parameter.rb
class Parameter < ApplicationRecord
  # has_many :search_parameters
  validates :weather_parameter, :weather_key, :activity_type, presence: true
end

app/controllers/parameters_controller.rb
class ParametersController < ApplicationController
  before_action :set_parameter, only: [:show, :destroy]
  def index
    @parameters = Parameter.all
  end

  def new
    @parameter = Parameter.new
  end

  def show
  end

  def create
    @parameter = Parameter.new(parameter_params)
    @parameter.save
    redirect_to new_parameter_path
  end

  def destroy
    @parameter.destroy
    redirect_to parameters_path
  end

  private

  def parameter_params
    params.require(:parameter).permit(:weather_parameter, :weather_key, :activity_type)
  end

  def set_parameter
    @parameter = Parameter.find(params[:id])
  end
end

app/helpers/parameters_helper.rb
module ParametersHelper
end

app/views/parameters/index.html.erb
<div>
<h3> Weather Parameters</h3>
<% @parameters.each do |parameter| %>
  <% if parameter.activity_type == "weather" %>
    <ul>
        <li><small> <%= parameter.weather_parameter %> </small> <small> <%= link_to "delete", parameter_path(parameter), method: :delete %></small></li>
    </ul>
  <%end %>
<% end %>
</div>

<div>
<h3>Marine Params</h3>
<% @parameters.each do |parameter|%>
  <% if parameter.activity_type == "marine" %>
    <ul>
        <li><small> <%= parameter.weather_parameter %> </small> <small> <%= link_to "delete", parameter_path(parameter), method: :delete %></small></li>
    </ul>
  <%end %>
<% end %>
</div>

app/views/parameters/new.html.erb
<div class="card sign">
<%= simple_form_for @parameter do |f| %>
  <%= f.input :weather_parameter, label: "Put the parameter name" %>
  <%= f.input :activity_type, collection: ["land activity", "water activity"], label: "Pick the type of activity" %>
  <%= f.input :weather_key, label: "Put the exact API key" %>
  <div class="form-actions text-center m-auto">
    <%= f.submit "create", class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/parameters/show.html.erb
<%= @parameter.weather_parameter %>
<%= @parameter.weather_key %>